version: 2.1
executors:
  exec:
    docker:
      - image: siredmar/mdcii-builder:latest

jobs:
  build:
    executor: exec
    steps:
      - checkout
      - run:
          name: Create build directories
          command: |
            mkdir -p build
      - run:
          name: Setup cmake and build artifacts
          command: |
            cd build
            cmake  ..
            cmake --build . --config Release
      - persist_to_workspace:
          root: .
          paths: build
